version: "3.7"
services:
#  server:
#    build:
#      context: .
#      dockerfile: ./server.dockerfile
#    container_name: custom-casts
#    entrypoint: /bin/bash
#    stdin_open: true
#    volumes:
#      - ./server:/app

  client:
    build:
      context: .
      dockerfile: ./client.dockerfile
    entrypoint: /bin/bash
    container_name: ocdevel-client
    ports:
      - 3003:3000  # main
      - 8003:8000  # gatsby
    stdin_open: true
    volumes:
      - ./client:/app
      - ./gatsby:/gatsby